### ISSUE TITLE
Support for a input file

### ISSUE THREAD

**Issue by kshitij10496** [sourcegraph/yj#1]
Hey! 

Thanks for the packages `yj` and `jy`. Both of these complement each other really well.

Currently, I want to use them in order to send config YAML files as encoded JSON strings via a network call and possibly provide a way to decode the JSON back to the original YAML.

It would be really useful if we can add support to accept an input YAML file instead.
```
$ yj old_config.yml -o new_config.json
$ jy new_config.json -o old_config.yml
```

Alternately, specifically for my usecase, I'd be happy with the `toJSON` functionality being exposed.
I would be happy to submit a PR with the changes for your review! 😃

**Comment by nicksnyder** [comment]
Glad you found `yj` and `jy` to be useful!

Does this not do what you want?

```
$ cat old_config.yml | yj -o new_config.json
$ cat new_config.json | jy -o old_config.yml
```

I would also accept a PR that allows the input file to be provided by positional argument if you think that is better.

> I'd be happy with the toJSON functionality being exposed.

You can submit a PR to expose this as a package if you want, but you could also just copy the code into your project.

**Comment by kshitij10496** [comment]
> Does this not do what you want?

That works for me, most definitely. Thanks! 😄 

> I would also accept a PR that allows the input file to be provided by positional argument if you think that is better.

I would be happy to open a PR. However, I noticed expecting the input file as a positional argument would most probably break the current interface for reading input from the `STDIN`, wouldn't it? Should we rather use the input file as an optional positional argument (or a flag `-i`) in order to have the best of both the worlds? Let me know how do you think we should approach this. 🤔 😃

**Comment by emidoots** [comment]
There is an easy to use / small library that you can pull in to detect if `os.Stdin` is a terminal or not. i.e., if stdin is a terminal you could use positional arguments, otherwise read from stdin if it is a pipe/file input.

We also do this in our CLI tool, see e.g. here: https://github.com/sourcegraph/src-cli/blob/master/cmd/src/api.go#L64-L65

(this is just one approach, of course)

**Comment by nicksnyder** [comment]
I don't think we need a library for this, the logic can be very simple:

If there are no position arguments, then read from stdin.
If there is one positional argument, then read from that file.
If there are more than one positional arguments, then error.

**Comment by kshitij10496** [comment]
> There is an easy to use / small library that you can pull in to detect if os.Stdin is a terminal or not. i.e., if stdin is a terminal you could use positional arguments, otherwise read from stdin if it is a pipe/file input.

Thanks for the heads up! 
The package is super cool and I love how it is being used in the CLI. 👏 

> I don't think we need a library for this, the logic can be very simple

I will implement it and send a PR right away! 😃
